### ISSUE TITLE
missing required field bidPrice

### ISSUE THREAD

**Issue by emekwi** [hyperledger/composer-sample-networks#107]
hello, 
while testing the car-auction example in composer i am getting this error ``` t: Instance org.acme.vehicle.auction.Offer#a50881fc-59d3-4982-bd9e-7af1d5531642 missing required field bidPrice``` when i run the closebidding transaction, can anyone tell me what is the issue?

**Comment by davidkel** [comment]
This is a duplicate of this problem https://github.com/hyperledger/composer/issues/2540
because the $class value is not set to the transaction you have selected.
