### ISSUE TITLE
No models files in vehicle-lifecycle-network 

### ISSUE THREAD

**Issue by aprilsnows** [hyperledger/composer-sample-networks#111]
Models files (.cto) are missing in  vehicle-lifecycle-network ?

**Comment by davidkel** [comment]
The model files can be found in the https://github.com/hyperledger/composer-sample-models repo, specifically
https://github.com/hyperledger/composer-sample-models/tree/master/packages/vehicle-lifecycle-model

**Comment by aprilsnows** [comment]
Thanks!
