### ISSUE TITLE
Hyperledger details

### ISSUE THREAD

**Issue by emekwi** [hyperledger/composer-sample-networks#113]
hello, can anyone help me with these question:  when we talk about the IBM blockchain or hypeledger, what blockchain this actually is and where does the code actually run, who participates in the blockchain network, where does the smart contract actually reside, who validates and how, etc.

**Comment by davidkel** [comment]
Information about hyperledger fabric can be found here
http://hyperledger-fabric.readthedocs.io/en/latest/
