### ISSUE TITLE
I cannot get the sample business networks to run

### ISSUE THREAD

**Issue by mcarvalho21** [hyperledger/composer-sample-networks#154]
I'm able to get the sample networks in the web-only mode, but not as an actual fabric instance. I'm trying to run a sample network that is included in Composer as a "Business network". I am able to create it without a problem but when I try to open it, I get the following error:

Error: Error trying to enroll user or load channel configuration. Error: Enrollment failed with errors [[{"code":400,"message":"Authorization failure"}]]

Followed the steps from the Composer tutorial, including for my Fabric instance, so I expect this to work.

Any ideas?

**Comment by gente21** [comment]
I can only run them with the manual steps on [https://hyperledger.github.io/composer/latest/tutorials/developer-tutorial.html](https://hyperledger.github.io/composer/latest/tutorials/developer-tutorial.html) but not from the playground, as you mention.

**Comment by davidkel** [comment]
Unable to recreate. Authorisation error indicates the wrong identity was being used. Would suggest clearing your card store 
```
rm -fr ${HOME}/.composer
```
And trying again.
