### ISSUE TITLE
carauction-network has no use for auctioneer

### ISSUE THREAD

**Issue by horeaporutiu** [hyperledger/composer-sample-networks#181]
From what I see in the model file + logic.js file, there is no use for the auctioneer. From my understanding, I would think it should be a requirement that only the auctioneer can submit the closeBidding transaction. 

I am working on implementing this pattern for Fabric Node.js SDK, so would be useful for me to know if I should implement the pattern as I have outlined above.

**Comment by davidkel** [comment]
Closing as no community activity.
