### ISSUE TITLE
How does composer archive map the correct network 

### ISSUE THREAD

**Issue by opiepj** [hyperledger/composer-sample-networks#52]
In the digitalproperty example:

When creating a archive:
`composer archive create --sourceType dir --sourceName . -a ./dist/digitalproperty-network.bna`

To me this looks like it would pick up `index.js` (due to `--sourceName .`), but `index.js` is empty... how does it pick up `lib/DigitalLandTitle.js`? How does this work?

**Comment by dselman** [comment]
Please post questions to StackOverflow.
