### ISSUE TITLE
No registered namespace for type org.example.mynetwork.Trade

### ISSUE THREAD

**Issue by ljbennett62** [hyperledger/composer-sample-networks#58]
I am following the tutorial under hyperledger Composer (https://hyperledger.github.io/composer/tutorials/developer-guide.html) and am getting the error when I do an ``npm install``.  I have Composer v0.8.0 installed
![composer-npminstallerror](https://user-images.githubusercontent.com/17774650/27410380-fea6d45a-569b-11e7-857e-9a1cbf3f9502.png)

**Comment by dselman** [comment]
Please try this again with v0.9 and reopen if still an issue.
