### ISSUE TITLE
Unable to deploy to V0.6

### ISSUE THREAD

**Issue by rddill-IBM** [hyperledger/composer-sample-networks#82]
Using this repo and the tutorial located here: https://hyperledger.github.io/composer/tutorials/developer-guide.html , I am unable to successfully deploy. 
```
composer network deploy --loglevel INFO -a ./dist/bd-test-network.bna -p hlfv0.6 -i PeerAdmin -s randomString
```
returns the following error every time: 
```
Deploying business network from archive: ./dist/bd-test-network.bna
Business network definition:
	Identifier: bd-test-network@0.1.5
	Description: The Hello World of Hyperledger Composer samples


Error: Identity lookup error: sql: no rows in result set
Command failed
```

I am working with V0.6 to build a tutorial for Bluemix. Currently the only available free version to developers is V0.6, so the current version of the tutorial is based on that release.  Have already reviewed [this stackoverflow question]([https://stackoverflow.com/questions/43408412/no-rows-in-result-set-when-trying-to-deploy-a-business-network](https://stackoverflow.com/questions/43408412/no-rows-in-result-set-when-trying-to-deploy-a-business-network)) 
https://stackoverflow.com/questions/43408412/no-rows-in-result-set-when-trying-to-deploy-a-business-network
but the provided guidance is based on V1 and the presence of a connection profile, neither of which are referenced in this repo or associated tutorial

**Comment by mbwhite** [comment]
Thank you for using composer - however as per release notes of v0.10.0 (https://github.com/hyperledger/composer/releases/tag/v0.10.0) support for v0.6 Fabric is deprecated and being removed entirely in v0.11.0

Fabric themselves are migrating all users to v1.0.

Therefore we can't keep supporting v0.6 Fabric.

**Comment by rddill-IBM** [comment]
Thanks for the response.
