### ISSUE TITLE
Issue in car auction model

### ISSUE THREAD

**Issue by melwynd** [hyperledger/composer-sample-networks#96]
If you create a vehicle with id as  just "1234", then close bidding function gives an error "Error: Object with ID 'vin:1234' in collection with ID 'Asset:org.acme.vehicle.auction.Vehicle' does not exist", even though the vehicle exists.
However if you create the vehicle as "vin:1234", then it works fine.

**Comment by nklincoln** [comment]
hi,
I just ran through this same scenario successfully - within the listing, did u also change the id to match?

ie "vehicle": "resource:org.acme.vehicle.auction.Vehicle#1234"

**Comment by melwynd** [comment]
Yes, I changed it in the "VehicleListing" as well.
Sorry, I should have mentioned, I'm trying out this sample at the IBM Bluemix simulator
http://composer-playground.mybluemix.net/

**Comment by nklincoln** [comment]
Hi,
I just ran the scenario through again on the link provided above and was able to go through the same scenario:
 - create auctioner
 - created member (owner)
 - created member (buyer)
 - created vehicle (id: 1234)
 - created listing
 - made offer from buyer
 - closed bidding

After bidding was closed, the vehicle ownership had changed (from owner to buyer) and members were also showing funds transfered

I'll keep running the scenario, and look at ways I may be able to drive the error you are seeing, but at the moment I can't recreate

**Comment by melwynd** [comment]
Sorry, my bad. I created another test scenario and It worked. You were right. When I had initially created the vehicle listing, I had not changed the ID of the car.
Sorry for the trouble.
